/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shresdip' at '05.11.15 16:26' with Gradle 2.6
 *
 * @author shresdip, @date 05.11.15 16:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
